"""
output/tid_formatter.py

TID report formatter for DeepThought.

Design goals:
1) Output both Markdown and HTML
2) Put summary and scorecard first
3) Keep full TID details in lower sections
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from html import escape
from io import BytesIO
from pathlib import Path
from typing import List


def _validate_star(value: int, name: str) -> int:
    if value < 1 or value > 5:
        raise ValueError(f"{name} must be between 1 and 5, got {value}")
    return value


def _stars(value: int) -> str:
    return f"[{value}/5]"


def _safe_text(value: str) -> str:
    return (value or "").strip()


@dataclass
class TIDScorecard:
    """Top-level scorecard shown near the top of the report."""

    innovation: int
    implementation_difficulty: int
    commercial_value: int
    technical_risk: int = 3
    prior_art_conflict_risk: int = 3

    def __post_init__(self) -> None:
        self.innovation = _validate_star(self.innovation, "innovation")
        self.implementation_difficulty = _validate_star(
            self.implementation_difficulty,
            "implementation_difficulty",
        )
        self.commercial_value = _validate_star(
            self.commercial_value,
            "commercial_value",
        )
        self.technical_risk = _validate_star(
            self.technical_risk,
            "technical_risk",
        )
        self.prior_art_conflict_risk = _validate_star(
            self.prior_art_conflict_risk,
            "prior_art_conflict_risk",
        )


@dataclass
class TIDSummary:
    """Executive summary shown before detailed sections."""

    one_liner: str
    novelty_thesis: str
    feasibility_thesis: str
    market_thesis: str
    why_now: str = ""


@dataclass
class TIDDetail:
    """Detailed TID body content shown after the summary."""

    problem_statement: str
    prior_art_gap: str
    proposed_invention: str
    architecture_overview: str
    implementation_plan: str
    validation_plan: str
    draft_claims: List[str] = field(default_factory=list)
    claim_confidence: List[str] = field(default_factory=list)
    prior_art_conflicts: List[str] = field(default_factory=list)
    risks_and_mitigations: List[str] = field(default_factory=list)
    references: List[str] = field(default_factory=list)


@dataclass
class TIDReport:
    """Single generated TID report with dual output formats."""

    tid_id: str
    title: str
    domain: str
    target: str
    summary: TIDSummary
    scorecard: TIDScorecard
    detail: TIDDetail
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    generated_by: str = "DeepThought"

    def to_markdown(self) -> str:
        claims_md = "\n".join(f"{i}. {c}" for i, c in enumerate(self.detail.draft_claims, start=1))
        if not claims_md:
            claims_md = "1. (No draft claims yet)"

        risks_md = "\n".join(f"- {r}" for r in self.detail.risks_and_mitigations)
        if not risks_md:
            risks_md = "- (No risk entries yet)"

        refs_md = "\n".join(f"- {r}" for r in self.detail.references)
        if not refs_md:
            refs_md = "- (No references yet)"

        confidence_md = "\n".join(f"- {x}" for x in self.detail.claim_confidence)
        if not confidence_md:
            confidence_md = "- (No claim confidence scores yet)"

        conflicts_md = "\n".join(f"- {x}" for x in self.detail.prior_art_conflicts)
        if not conflicts_md:
            conflicts_md = "- (No explicit prior-art conflicts detected)"

        return f"""# {self.title}

TID ID: {self.tid_id}
Generated By: {self.generated_by}
Generated At (UTC): {self.created_at.isoformat(timespec='seconds')}
Domain: {self.domain}
Target: {self.target}

## 1. Executive Summary

### 1.1 One-Liner
{_safe_text(self.summary.one_liner)}

### 1.2 Key Angles
- Novelty: {_safe_text(self.summary.novelty_thesis)}
- Feasibility: {_safe_text(self.summary.feasibility_thesis)}
- Commercial Value: {_safe_text(self.summary.market_thesis)}
- Why Now: {_safe_text(self.summary.why_now) or "N/A"}

## 2. Scorecard (1-5)

| Dimension | Score | Rating |
|---|---:|---|
| Innovation | {self.scorecard.innovation}/5 | {_stars(self.scorecard.innovation)} |
| Implementation Difficulty | {self.scorecard.implementation_difficulty}/5 | {_stars(self.scorecard.implementation_difficulty)} |
| Commercial Value | {self.scorecard.commercial_value}/5 | {_stars(self.scorecard.commercial_value)} |
| Technical Risk | {self.scorecard.technical_risk}/5 | {_stars(self.scorecard.technical_risk)} |
| Prior-Art Conflict Risk | {self.scorecard.prior_art_conflict_risk}/5 | {_stars(self.scorecard.prior_art_conflict_risk)} |

## 3. Detailed TID

### 3.1 Problem Statement
{_safe_text(self.detail.problem_statement)}

### 3.2 Prior-Art Gap (Topological Void)
{_safe_text(self.detail.prior_art_gap)}

### 3.3 Proposed Invention
{_safe_text(self.detail.proposed_invention)}

### 3.4 Architecture Overview
{_safe_text(self.detail.architecture_overview)}

### 3.5 Implementation Plan
{_safe_text(self.detail.implementation_plan)}

### 3.6 Validation Plan
{_safe_text(self.detail.validation_plan)}

### 3.7 Draft Claims
{claims_md}

### 3.8 Risks and Mitigations
{risks_md}

### 3.9 References
{refs_md}

### 3.10 Claim Confidence Scores
{confidence_md}

### 3.11 Prior-Art Conflict Detector
{conflicts_md}
"""

    def to_html(self) -> str:
        def p(text: str) -> str:
            return f"<p>{escape(_safe_text(text) or 'N/A')}</p>"

        claims_html = "".join(
            f"<li>{escape(c)}</li>" for c in self.detail.draft_claims
        ) or "<li>(No draft claims yet)</li>"

        risks_html = "".join(
            f"<li>{escape(r)}</li>" for r in self.detail.risks_and_mitigations
        ) or "<li>(No risk entries yet)</li>"

        refs_html = "".join(
            f"<li>{escape(r)}</li>" for r in self.detail.references
        ) or "<li>(No references yet)</li>"

        confidence_html = "".join(
            f"<li>{escape(x)}</li>" for x in self.detail.claim_confidence
        ) or "<li>(No claim confidence scores yet)</li>"

        conflicts_html = "".join(
            f"<li>{escape(x)}</li>" for x in self.detail.prior_art_conflicts
        ) or "<li>(No explicit prior-art conflicts detected)</li>"

        return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{escape(self.title)}</title>
  <style>
    :root {{
      --bg: #f7f7f4;
      --card: #ffffff;
      --ink: #1f2328;
      --muted: #59636e;
      --line: #dde2e7;
      --accent: #0b5fff;
      --star: #d99a00;
    }}
    body {{
      margin: 0;
      background: radial-gradient(circle at 20% 0%, #eef3ff, var(--bg) 42%);
      color: var(--ink);
      font: 15px/1.6 "Segoe UI", "Noto Sans", sans-serif;
    }}
    .wrap {{ max-width: 1024px; margin: 0 auto; padding: 28px 16px 72px; }}
    .card {{
      background: var(--card);
      border: 1px solid var(--line);
      border-radius: 14px;
      padding: 18px;
      margin-bottom: 14px;
    }}
    h1, h2, h3 {{ margin: 0 0 10px; }}
    h1 {{ font-size: 28px; }}
    h2 {{ font-size: 20px; border-bottom: 1px solid var(--line); padding-bottom: 6px; }}
    h3 {{ font-size: 16px; color: var(--muted); }}
    .meta {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 8px; }}
    .pill {{ background: #f2f5f8; border: 1px solid var(--line); border-radius: 999px; padding: 4px 10px; display: inline-block; margin: 4px 6px 0 0; }}
    table {{ width: 100%; border-collapse: collapse; }}
    th, td {{ border-bottom: 1px solid var(--line); text-align: left; padding: 8px 6px; }}
    .stars {{ color: var(--star); letter-spacing: 1px; }}
    .muted {{ color: var(--muted); }}
    ul, ol {{ margin: 8px 0 0 20px; }}
  </style>
</head>
<body>
  <div class="wrap">
    <section class="card">
      <h1>{escape(self.title)}</h1>
      <div class="meta muted">
        <div><strong>TID ID:</strong> {escape(self.tid_id)}</div>
        <div><strong>Generated By:</strong> {escape(self.generated_by)}</div>
        <div><strong>Generated At (UTC):</strong> {escape(self.created_at.isoformat(timespec='seconds'))}</div>
        <div><strong>Domain:</strong> {escape(self.domain)}</div>
        <div><strong>Target:</strong> {escape(self.target)}</div>
      </div>
    </section>

    <section class="card">
      <h2>1. Executive Summary</h2>
      <h3>1.1 One-Liner</h3>
      {p(self.summary.one_liner)}
      <h3>1.2 Key Angles</h3>
      <div class="pill"><strong>Novelty:</strong> {escape(_safe_text(self.summary.novelty_thesis) or 'N/A')}</div>
      <div class="pill"><strong>Feasibility:</strong> {escape(_safe_text(self.summary.feasibility_thesis) or 'N/A')}</div>
      <div class="pill"><strong>Commercial Value:</strong> {escape(_safe_text(self.summary.market_thesis) or 'N/A')}</div>
      <div class="pill"><strong>Why Now:</strong> {escape(_safe_text(self.summary.why_now) or 'N/A')}</div>
    </section>

    <section class="card">
      <h2>2. Scorecard (1-5)</h2>
      <table>
        <thead>
          <tr><th>Dimension</th><th>Score</th><th>Rating</th></tr>
        </thead>
        <tbody>
          <tr><td>Innovation</td><td>{self.scorecard.innovation}/5</td><td class="stars">{_stars(self.scorecard.innovation)}</td></tr>
          <tr><td>Implementation Difficulty</td><td>{self.scorecard.implementation_difficulty}/5</td><td class="stars">{_stars(self.scorecard.implementation_difficulty)}</td></tr>
          <tr><td>Commercial Value</td><td>{self.scorecard.commercial_value}/5</td><td class="stars">{_stars(self.scorecard.commercial_value)}</td></tr>
          <tr><td>Technical Risk</td><td>{self.scorecard.technical_risk}/5</td><td class="stars">{_stars(self.scorecard.technical_risk)}</td></tr>
          <tr><td>Prior-Art Conflict Risk</td><td>{self.scorecard.prior_art_conflict_risk}/5</td><td class="stars">{_stars(self.scorecard.prior_art_conflict_risk)}</td></tr>
        </tbody>
      </table>
    </section>

    <section class="card">
      <h2>3. Detailed TID</h2>
      <h3>3.1 Problem Statement</h3>
      {p(self.detail.problem_statement)}
      <h3>3.2 Prior-Art Gap (Topological Void)</h3>
      {p(self.detail.prior_art_gap)}
      <h3>3.3 Proposed Invention</h3>
      {p(self.detail.proposed_invention)}
      <h3>3.4 Architecture Overview</h3>
      {p(self.detail.architecture_overview)}
      <h3>3.5 Implementation Plan</h3>
      {p(self.detail.implementation_plan)}
      <h3>3.6 Validation Plan</h3>
      {p(self.detail.validation_plan)}
      <h3>3.7 Draft Claims</h3>
      <ol>{claims_html}</ol>
      <h3>3.8 Risks and Mitigations</h3>
      <ul>{risks_html}</ul>
      <h3>3.9 References</h3>
      <ul>{refs_html}</ul>
        <h3>3.10 Claim Confidence Scores</h3>
        <ul>{confidence_html}</ul>
        <h3>3.11 Prior-Art Conflict Detector</h3>
        <ul>{conflicts_html}</ul>
    </section>
  </div>
</body>
</html>
"""

    def to_docx_bytes(self) -> bytes:
        try:
            from docx import Document
        except Exception as exc:  # pragma: no cover - optional dependency
            raise RuntimeError("python-docx is required for DOCX export") from exc

        doc = Document()
        doc.add_heading(self.title, level=1)
        doc.add_paragraph(f"TID ID: {self.tid_id}")
        doc.add_paragraph(f"Domain: {self.domain}")
        doc.add_paragraph(f"Target: {self.target}")
        doc.add_heading("Executive Summary", level=2)
        doc.add_paragraph(self.summary.one_liner)
        doc.add_paragraph(f"Novelty: {self.summary.novelty_thesis}")
        doc.add_paragraph(f"Feasibility: {self.summary.feasibility_thesis}")
        doc.add_heading("Claims", level=2)
        for claim in self.detail.draft_claims:
            doc.add_paragraph(claim, style="List Number")
        doc.add_heading("Claim Confidence", level=2)
        for line in self.detail.claim_confidence:
            doc.add_paragraph(line, style="List Bullet")
        doc.add_heading("Prior-Art Conflicts", level=2)
        for line in self.detail.prior_art_conflicts:
            doc.add_paragraph(line, style="List Bullet")

        buffer = BytesIO()
        doc.save(buffer)
        return buffer.getvalue()

    def to_pdf_bytes(self) -> bytes:
        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.pdfgen import canvas
        except Exception as exc:  # pragma: no cover - optional dependency
            raise RuntimeError("reportlab is required for PDF export") from exc

        buffer = BytesIO()
        c = canvas.Canvas(buffer, pagesize=A4)
        width, height = A4
        x = 40
        y = height - 40

        def write_line(text: str) -> None:
            nonlocal y
            if y < 60:
                c.showPage()
                y = height - 40
            c.drawString(x, y, (text or "")[:120])
            y -= 14

        write_line(self.title)
        write_line(f"TID ID: {self.tid_id}")
        write_line(f"Domain: {self.domain} | Target: {self.target}")
        write_line("Claims:")
        for idx, claim in enumerate(self.detail.draft_claims, start=1):
            write_line(f"{idx}. {claim}")
        write_line("Claim Confidence:")
        for line in self.detail.claim_confidence:
            write_line(f"- {line}")
        write_line("Prior-Art Conflicts:")
        for line in self.detail.prior_art_conflicts:
            write_line(f"- {line}")

        c.save()
        return buffer.getvalue()

    def save(self, output_dir: Path | str, base_name: str | None = None) -> tuple[Path, Path]:
        out_dir = Path(output_dir)
        out_dir.mkdir(parents=True, exist_ok=True)

        base = base_name or f"{self.tid_id}_{self.created_at.strftime('%Y%m%d_%H%M%S')}"
        md_path = out_dir / f"{base}.md"
        html_path = out_dir / f"{base}.html"

        md_path.write_text(self.to_markdown(), encoding="utf-8")
        html_path.write_text(self.to_html(), encoding="utf-8")
        return md_path, html_path

    def save_extended(self, output_dir: Path | str, base_name: str | None = None) -> dict[str, str]:
        md_path, html_path = self.save(output_dir=output_dir, base_name=base_name)
        base = md_path.with_suffix("")
        output = {
            "markdown": str(md_path),
            "html": str(html_path),
            "docx": "",
            "pdf": "",
        }

        docx_path = base.with_suffix(".docx")
        pdf_path = base.with_suffix(".pdf")

        try:
            docx_path.write_bytes(self.to_docx_bytes())
            output["docx"] = str(docx_path)
        except RuntimeError:
            pass

        try:
            pdf_path.write_bytes(self.to_pdf_bytes())
            output["pdf"] = str(pdf_path)
        except RuntimeError:
            pass

        return output
